// Code generated by protoc-gen-go.
// source: calc.proto
// DO NOT EDIT!

/*
Package calc is a generated protocol buffer package.

It is generated from these files:
	calc.proto

It has these top-level messages:
	Result
	Numbers
*/
package calc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Result struct {
	Value      float64 `protobuf:"fixed64,1,opt,name=value" json:"value,omitempty"`
	Err        bool    `protobuf:"varint,2,opt,name=err" json:"err,omitempty"`
	ErrMessage string  `protobuf:"bytes,3,opt,name=err_message,json=errMessage" json:"err_message,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Result) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Result) GetErr() bool {
	if m != nil {
		return m.Err
	}
	return false
}

func (m *Result) GetErrMessage() string {
	if m != nil {
		return m.ErrMessage
	}
	return ""
}

type Numbers struct {
	X float64 `protobuf:"fixed64,1,opt,name=x" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y" json:"y,omitempty"`
}

func (m *Numbers) Reset()                    { *m = Numbers{} }
func (m *Numbers) String() string            { return proto.CompactTextString(m) }
func (*Numbers) ProtoMessage()               {}
func (*Numbers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Numbers) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Numbers) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*Result)(nil), "Result")
	proto.RegisterType((*Numbers)(nil), "Numbers")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Calculator service

type CalculatorClient interface {
	Add(ctx context.Context, in *Numbers, opts ...grpc.CallOption) (*Result, error)
	Sub(ctx context.Context, in *Numbers, opts ...grpc.CallOption) (*Result, error)
	Mul(ctx context.Context, in *Numbers, opts ...grpc.CallOption) (*Result, error)
	Div(ctx context.Context, in *Numbers, opts ...grpc.CallOption) (*Result, error)
}

type calculatorClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorClient(cc *grpc.ClientConn) CalculatorClient {
	return &calculatorClient{cc}
}

func (c *calculatorClient) Add(ctx context.Context, in *Numbers, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/Calculator/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorClient) Sub(ctx context.Context, in *Numbers, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/Calculator/Sub", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorClient) Mul(ctx context.Context, in *Numbers, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/Calculator/Mul", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorClient) Div(ctx context.Context, in *Numbers, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/Calculator/Div", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Calculator service

type CalculatorServer interface {
	Add(context.Context, *Numbers) (*Result, error)
	Sub(context.Context, *Numbers) (*Result, error)
	Mul(context.Context, *Numbers) (*Result, error)
	Div(context.Context, *Numbers) (*Result, error)
}

func RegisterCalculatorServer(s *grpc.Server, srv CalculatorServer) {
	s.RegisterService(&_Calculator_serviceDesc, srv)
}

func _Calculator_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Numbers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calculator/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Add(ctx, req.(*Numbers))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calculator_Sub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Numbers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Sub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calculator/Sub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Sub(ctx, req.(*Numbers))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calculator_Mul_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Numbers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Mul(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calculator/Mul",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Mul(ctx, req.(*Numbers))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calculator_Div_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Numbers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Div(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calculator/Div",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Div(ctx, req.(*Numbers))
	}
	return interceptor(ctx, in, info, handler)
}

var _Calculator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Calculator",
	HandlerType: (*CalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Calculator_Add_Handler,
		},
		{
			MethodName: "Sub",
			Handler:    _Calculator_Sub_Handler,
		},
		{
			MethodName: "Mul",
			Handler:    _Calculator_Mul_Handler,
		},
		{
			MethodName: "Div",
			Handler:    _Calculator_Div_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calc.proto",
}

func init() { proto.RegisterFile("calc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4e, 0xcc, 0x49,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x0a, 0xe4, 0x62, 0x0b, 0x4a, 0x2d, 0x2e, 0xcd, 0x29,
	0x11, 0x12, 0xe1, 0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0c,
	0x82, 0x70, 0x84, 0x04, 0xb8, 0x98, 0x53, 0x8b, 0x8a, 0x24, 0x98, 0x14, 0x18, 0x35, 0x38, 0x82,
	0x40, 0x4c, 0x21, 0x79, 0x2e, 0xee, 0xd4, 0xa2, 0xa2, 0xf8, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4,
	0x54, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xce, 0x20, 0xae, 0xd4, 0xa2, 0x22, 0x5f, 0x88, 0x88, 0x92,
	0x2a, 0x17, 0xbb, 0x5f, 0x69, 0x6e, 0x52, 0x6a, 0x51, 0xb1, 0x10, 0x0f, 0x17, 0x63, 0x05, 0xd4,
	0x3c, 0xc6, 0x0a, 0x10, 0xaf, 0x12, 0x6c, 0x12, 0x63, 0x10, 0x63, 0xa5, 0x51, 0x0d, 0x17, 0x97,
	0x73, 0x62, 0x4e, 0x72, 0x69, 0x4e, 0x62, 0x49, 0x7e, 0x91, 0x90, 0x14, 0x17, 0xb3, 0x63, 0x4a,
	0x8a, 0x10, 0x87, 0x1e, 0x54, 0xab, 0x14, 0xbb, 0x1e, 0xc4, 0x5d, 0x4a, 0x0c, 0x20, 0xb9, 0xe0,
	0xd2, 0x24, 0x9c, 0x72, 0xbe, 0xa5, 0x39, 0x38, 0xe5, 0x5c, 0x32, 0xcb, 0xb0, 0xca, 0x25, 0xb1,
	0x81, 0xbd, 0x6f, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x6d, 0xff, 0xc4, 0x0c, 0x01, 0x00,
	0x00,
}
